apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: default
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: https://github.com/kankun92/argocd-app-config-main
    path: hello-world.yaml
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      post:
        - name: notify-microsoft-teams
          hook:
            afterSync: true
            command: ["/bin/sh", "-c", "kubectl apply -f notification-job.yaml"]
  project: default